[build-system]
requires = ["uv_build>=0.9.27,<0.10.0"]
build-backend = "uv_build"

[project]
name = "coding-guidelines-ext"
version = "0.1.0"
requires-python = ">=3.12,<3.13"

[tool.uv.build-backend]
module-root = "."
module-name = "coding_guidelines"
